name: Daily Thriller Post
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install requests
      - name: Run Bot
        env:
          PA_API_KEY:    ${{ secrets.PA_API_KEY }}
          PA_API_SECRET: ${{ secrets.PA_API_SECRET }}
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          PAGE_ID:       ${{ secrets.PAGE_ID }}
        run: python bot.py
